### ISSUE TITLE
Question: how to login after machine is provisioned

### ISSUE THREAD

**Issue by JamborJan** [tobru/kolab3-vagrant#3]
When the machine is provisioned I can access: 
- http://localhost:8080/roundcubemail/
- http://localhost:8080/kolab-webadmin/

Which users do I use to access that. There is a ton of Admin being generated during the provisioning process but none works for me.

Maybe a stupid question, sorry for that ...

**Comment by tobru** [comment]
You can find more information here: https://docs.kolab.org/installation-guide/first-login.html
In short: log in to http://localhost:8080/kolab-webadmin/ with the user "cn=Directory Manager" and the generated password (setup-kolab) called "Directory Manager password". There you can create a user which then can be used to log in to the webmail. **Note**: Make sure you follow the [README](https://github.com/tobru/kolab3-vagrant#api_url-for-nated-ports) for the `api_url` change.

**Comment by JamborJan** [comment]
I'm not sure if you are the right person to ask this question as I don't know if you are related to kolab or not so please feel free to say "go to kolab".

What you say and what is written in the docs is unfortunately not working for me, or I'm doing it wrong.

I have setup kolab via `setup-kolab` and accepted the given passwords by confirming the randomized suggested passwords (example on the pic below):

![bildschirmfoto 2015-08-11 um 16 59 40](https://cloud.githubusercontent.com/assets/7508960/9205835/bf996dda-4064-11e5-8b0a-8e0660451472.png)

I can access `http://localhost:8080/kolab-webadmin` then but a error message is shown: 

```
Internal system error!
```

![bildschirmfoto 2015-08-11 um 17 00 19](https://cloud.githubusercontent.com/assets/7508960/9205838/c6c2a86a-4064-11e5-9635-c63bd4e7148d.png)

Same happens for me when I try to set the password manually and do not accept the randomized suggestions.

**Comment by tobru** [comment]
That looks like you didn't update the `api_url` like it is described here: [README](https://github.com/tobru/kolab3-vagrant#api_url-for-nated-ports). Please check that setting...
